<?php   
return   [
                Tables\Columns\TextColumn::make('student_id')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('id_pfe')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('organization_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('adresse')
                    ->searchable(),
                Tables\Columns\TextColumn::make('city')
                    ->searchable(),
                Tables\Columns\TextColumn::make('country')
                    ->searchable(),
                Tables\Columns\TextColumn::make('office_location')
                    ->searchable(),
                Tables\Columns\TextColumn::make('parrain_titre')
                    ->searchable(),
                Tables\Columns\TextColumn::make('parrain_nom')
                    ->searchable(),
                Tables\Columns\TextColumn::make('parrain_prenom')
                    ->searchable(),
                Tables\Columns\TextColumn::make('parrain_fonction')
                    ->searchable(),
                Tables\Columns\TextColumn::make('parrain_tel')
                    ->searchable(),
                Tables\Columns\TextColumn::make('parrain_mail')
                    ->searchable(),
                Tables\Columns\TextColumn::make('encadrant_ext_titre')
                    ->searchable(),
                Tables\Columns\TextColumn::make('encadrant_ext_nom')
                    ->searchable(),
                Tables\Columns\TextColumn::make('encadrant_ext_prenom')
                    ->searchable(),
                Tables\Columns\TextColumn::make('encadrant_ext_fonction')
                    ->searchable(),
                Tables\Columns\TextColumn::make('encadrant_ext_tel')
                    ->searchable(),
                Tables\Columns\TextColumn::make('encadrant_ext_mail')
                    ->searchable(),
                Tables\Columns\TextColumn::make('starting_at')
                    ->date()
                    ->sortable(),
                Tables\Columns\TextColumn::make('ending_at')
                    ->date()
                    ->sortable(),
                Tables\Columns\TextColumn::make('remuneration')
                    ->searchable(),
                Tables\Columns\TextColumn::make('currency')
                    ->searchable(),
                Tables\Columns\TextColumn::make('load')
                    ->searchable(),
                Tables\Columns\TextColumn::make('int_adviser_name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('year_id')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\IconColumn::make('is_valid')
                    ->boolean(),
                Tables\Columns\TextColumn::make('status')
                    ->searchable(),
                Tables\Columns\TextColumn::make('announced_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('validated_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('assigned_department')
                    ->searchable(),
                Tables\Columns\TextColumn::make('received_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('signed_at')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('project_id')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('binome_user_id')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('partner_internship_id')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('partnership_status')
                    ->searchable(),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('deleted_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ]