name: Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync repository files to server with rsync
        run: |
          rsync -avz --delete-after --exclude 'storage' --exclude '.env' --exclude 'vendor' --exclude 'public' -e "ssh -o StrictHostKeyChecking=no" ./ elmeliani@carrieres.inpt.ac.ma:/tmp/careers_backend_temp

      - name: Move files and execute deployment script on server
        run: |
          ssh -o StrictHostKeyChecking=no elmeliani@carrieres.inpt.ac.ma 'rsync -avz --exclude storage --exclude public --exclude .env --exclude vendor /tmp/careers_backend_temp/ /var/www/html/careers_backend/'
     - name: deploy css and js
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i private_key" public/build/ elmeliani@carrieres.inpt.ac.ma:/var/www/html/careers_backend/public/build/
          ssh -o StrictHostKeyChecking=no -i private_key elmeliani@carrieres.inpt.ac.ma "cd /var/www/html/careers_backend && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan cache:clear"
