name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true # Clone submodules

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, bcmath, zip

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install PHP Dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction

      - name: Install Node Dependencies & Build
        run: |
          npm ci
          npm run build

      - name: Set initial permissions on server
        run: |
          ssh -o StrictHostKeyChecking=no elmeliani@carrieres.inpt.ac.ma '
            sudo chown -R elmeliani:caddy /var/www/html/careers_backend
          '

      - name: Sync files to server
        run: |
          rsync -rltDz \
          --omit-dir-times \
          --no-perms \
          --no-owner \
          --no-group \
          --exclude='.git*' \
          --exclude='storage/app/*' \
          --exclude='storage/framework/cache/*' \
          --exclude='storage/framework/sessions/*' \
          --exclude='storage/framework/views/*' \
          --exclude='storage/logs/*' \
          --exclude='.env' \
          --exclude='node_modules' \
          --exclude='tests' \
          --exclude='vendor/parfaitementweb/filament-country-field' \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ elmeliani@carrieres.inpt.ac.ma:/var/www/html/careers_backend/

      - name: Update Git repository state
        run: |
          ssh -o StrictHostKeyChecking=no elmeliani@carrieres.inpt.ac.ma '
            cd /var/www/html/careers_backend && \
            git fetch && \
            git reset --hard origin/main && \
            git clean -fd
          '

      - name: Sync filament-country-field package
        run: |
          rsync -rltDz \
          --omit-dir-times \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./vendor/parfaitementweb/filament-country-field/ \
          elmeliani@carrieres.inpt.ac.ma:/var/www/html/careers_backend/vendor/parfaitementweb/filament-country-field/

      - name: Execute deployment commands
        run: |
          ssh -o StrictHostKeyChecking=no elmeliani@carrieres.inpt.ac.ma '
            cd /var/www/html/careers_backend && \
            php artisan down && \
            php artisan config:clear && \
            php artisan cache:clear && \
            php artisan view:clear && \
            php artisan route:clear && \
            php artisan icons:clear && \
            sudo find . -type f -exec chmod 664 {} \; && \
            sudo find . -type d -exec chmod 775 {} \; && \
            sudo chown -R caddy:caddy . && \
            sudo chmod -R 775 storage bootstrap/cache && \
            php artisan config:cache && \
            php artisan route:cache && \
            php artisan view:cache && \
            php artisan icons:cache && \
            php artisan filament:cache-components && \
            php artisan migrate --force && \
            php artisan storage:link && \
            php artisan up
          '
