name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true # Clone submodules

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, bcmath, zip

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-scripts --no-progress --optimize-autoloader

      - name: Install NPM dependencies
        run: npm install

      - name: Build assets
        run: npm run prod

      - name: Set correct permissions on server
        run: |
          ssh -o StrictHostKeyChecking=no elmeliani@carrieres.inpt.ac.ma '
            sudo chown -R elmeliani:elmeliani /var/www/html/careers_backend && \
            sudo chmod -R 775 /var/www/html/careers_backend
          '

      - name: Sync files to server
        run: |
          rsync -rlz --delete-after \
          --omit-dir-times \
          --no-perms \
          --no-owner \
          --no-group \
          --exclude='.git*' \
          --exclude='storage/app/*' \
          --exclude='storage/framework/cache/*' \
          --exclude='storage/framework/sessions/*' \
          --exclude='storage/framework/views/*' \
          --exclude='storage/logs/*' \
          --exclude='.env' \
          --exclude='node_modules' \
          --exclude='tests' \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ elmeliani@carrieres.inpt.ac.ma:/var/www/html/careers_backend/

      - name: Execute deployment commands
        run: |
          ssh -o StrictHostKeyChecking=no elmeliani@carrieres.inpt.ac.ma '
            cd /var/www/html/careers_backend && \
            php artisan down --message="We are updating" && \
            php artisan config:clear && \
            php artisan cache:clear && \
            php artisan view:clear && \
            php artisan route:clear && \
            php artisan icons:clear && \
            php artisan config:cache && \
            php artisan route:cache && \
            php artisan view:cache && \
            php artisan icons:cache && \
            php artisan filament:cache-components && \
            php artisan migrate --force && \
            php artisan storage:link && \
            sudo chmod -R 775 storage bootstrap/cache && \
            sudo chown -R caddy:caddy . && \
            php artisan up
          '
