name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, bcmath, zip

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install PHP Dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction

      - name: Install Node Dependencies & Build
        run: |
          npm ci
          npm run build

      - name: Sync files to server
        run: |
          rsync -avz --delete-after \
          --exclude='.git*' \
          --exclude='storage/app/*' \
          --exclude='storage/framework/cache/*' \
          --exclude='storage/framework/sessions/*' \
          --exclude='storage/framework/views/*' \
          --exclude='storage/logs/*' \
          --exclude='.env' \
          --exclude='node_modules' \
          --exclude='tests' \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ elmeliani@carrieres.inpt.ac.ma:/var/www/html/careers_backend/

      - name: Execute deployment commands
        run: |
          ssh -o StrictHostKeyChecking=no elmeliani@carrieres.inpt.ac.ma 'cd /var/www/html/careers_backend && \
          php artisan down && \
          php artisan config:clear && \
          php artisan cache:clear && \
          php artisan view:clear && \
          php artisan route:clear && \
          php artisan icons:clear && \
          php artisan config:cache && \
          php artisan route:cache && \
          php artisan view:cache && \
          php artisan icons:cache && \
          php artisan filament:cache-components && \
          php artisan migrate --force && \
          php artisan storage:link && \
          chmod -R 775 storage bootstrap/cache && \
          chown -R caddy:caddy . && \
          php artisan up'
