name: Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Execute deployment script
        run: |
          ssh -o StrictHostKeyChecking=no elmeliani@carrieres.inpt.ac.ma 'cd /var/www/html/careers_backend && git pull && composer install && ./sys/cache'
